### PR TITLE
chore: move subscribers to new service

### PR DESCRIPTION
**Pull request by Ubisoft-potato**
This PR will remove all subscribers from the batch service and then establish a service named `subscriber`. This allows for separate management of all subscribers.

## Key changes

- Remove subscribers from batch service.
- Create `subscriber` service. [[1]](https://github.com/bucketeer-io/bucketeer/pull/1168/files#diff-ab3fb804d3d01f7a6bfb86607e8e28267bd5c29059bf566bba186f4c3abf8634) [[2]](https://github.com/bucketeer-io/bucketeer/pull/1168/files#diff-a09cb6023f8ef28461a327cd799966e48de13b6c94b9cc96ca774fdbd79946ea)
- We don't need ingress in `subscriber` service envoy config. [[1]](https://github.com/bucketeer-io/bucketeer/pull/1168/files#diff-21ff834f910ef8890e89bc52d43c5c2e9674313baf6802bf0da48f7b462ef811R99)

### CODE REVIEW

**Comment by cre8ivejp** [comment]
@Ubisoft-potato, please fix the conflict.

**Comment by Ubisoft-potato** [comment]
> @Ubisoft-potato, please fix the conflict.

Fixed!

**Review by kentakozuka — APPROVED** [review]
Thanks! LGTM 👍

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Pull request merged**
