### PR TITLE
refactor: remove env variables for alloydb

### PR DESCRIPTION
**Pull request by ono-max**
https://github.com/bucketeer-io/bucketeer/pull/65#discussion_r1016287458

### CODE REVIEW

**Review by masaaania — APPROVED** [review]
👍 👍

**Review by cre8ivejp — DISMISSED** [review]
Thanks!

**Comment by cre8ivejp** [comment]
@ono-max, please fix the conflicts so we can merge this.

**Review by cre8ivejp — APPROVED** [review]
👍

**Pull request merged**
