### PR TITLE
refactor: web-v2-app-admin support absolute import

### PR DESCRIPTION
**Pull request by ta1m1kam**
absolute-path

I adapted only one file since there are many target files.

### CODE REVIEW

**Comment by ta1m1kam** [comment]
I don't know why argo-ci failed :bow:
スクリーンショット 2022-09-30 22 29 51

**Comment by cre8ivejp** [comment]
@ta1m1kam 
Thanks a lot for your contribution!
We appreciate it.

I'm sorry for the delay. The CI configuration didn't support forked repositories.
While I fixed it, you still can't see the result logs because the CI website it's for internal use.
We are going to move our CI from Argo to GitHub Actions soon, so everyone will be able to see the logs.

**Comment by ta1m1kam** [comment]
@cre8ivejp 
no worries!!
Thank you for making great oss and your response.

**Comment by cre8ivejp** [comment]
recheck

**Comment by cre8ivejp** [comment]
@ta1m1kam Hi!
Before merging your PR, I kindly ask you to sign our CLA.
You can check more info on this [comment](https://github.com/bucketeer-io/bucketeer/pull/3#issuecomment-1267893612). If it is ok, you just need to comment `/cla sign`.

Thank you!

**Comment by ta1m1kam** [comment]
@cre8ivejp ↑ is it OK?

**Review by cre8ivejp — APPROVED** [review]
Thanks a lot 🎉

**Pull request merged**
