### PR TITLE
chore: update redis default settings

### PR DESCRIPTION
**Pull request by cre8ivejp**

### CODE REVIEW

**Comment by ono-max** [comment]
Perhaps, we should remove https://github.com/bucketeer-io/bucketeer/blob/ea5865332dabeabaa99ab01b783af8029e3be529/manifests/bucketeer/values.yaml#L1522?

**Review by ono-max — DISMISSED** [review]
👍

**Comment by cre8ivejp** [comment]
@ono-max 
Thanks, I have updated it.

**Review by ono-max — APPROVED** [review]
👍

**Pull request merged**
