### PR TITLE
chore: remove segment persister

### PR DESCRIPTION
**Pull request by Ubisoft-potato**
Since we have already [moved segmentpersister to batch servcice](https://github.com/bucketeer-io/bucketeer/pull/896), so we can delete original code in `feature` module.

### CODE REVIEW

**Review by kentakozuka — DISMISSED** [review]
LGTM 👍

**Comment by cre8ivejp** [comment]
@Ubisoft-potato, please delete the manifest files.

**Comment by Ubisoft-potato** [comment]
> @Ubisoft-potato, please delete the manifest files.

Done!

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Pull request merged**
