### PR TITLE
refactor: use type for form schema in feature page

### PR DESCRIPTION
**Pull request by kentakozuka**
part of https://github.com/bucketeer-io/bucketeer/issues/1017

### CODE REVIEW

**Comment by cre8ivejp** [comment]
@kentakozuka, the changes are causing many errors in the console.

Screenshot 2024-06-14 at 12 19 33 PM

Also, on the targeting tab, the off variation is not showing.
Probably there are more issues.

Screenshot 2024-06-14 at 12 21 59 PM

**Comment by kentakozuka** [comment]
@cre8ivejp Are you using Firefox?

**Comment by kentakozuka** [comment]
@cre8ivejp OffVariation issue is fixed 👍

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Pull request merged**
