### PR TITLE
build: add code-butler

### PR DESCRIPTION
**Pull request by ouchi2501**
## Overview
Code-Butler is a tool that utilizes AI to conduct code reviews.
I believe that implementing this tool will be helpful for our code review process.
Swift code reviews are also crucial for development productivity.

## Ref
https://github.com/ca-dp/code-butler

## Note
OPENAI_API_KEY must be set in Repository secrets of Actions.

### CODE REVIEW

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Review by masaaania — APPROVED** [review]
Thank you! LGTM 🎉

**Comment by ouchi2501** [comment]
I have confirmed that it is working correctly.
https://github.com/bucketeer-io/bucketeer/actions/runs/6781271185

**Pull request merged**
