### PR TITLE
feat: feature can be set in targeting

### PR DESCRIPTION
**Pull request by kentakozuka**
part of https://github.com/bucketeer-io/bucketeer/issues/963

### CODE REVIEW

**Comment by kentakozuka** [comment]
@cre8ivejp fixed 👍

**Comment by cre8ivejp** [comment]
> @cre8ivejp fixed 👍

How about validating on the server?

**Comment by kentakozuka** [comment]
We have validation on server side here
https://github.com/bucketeer-io/bucketeer/blob/25ed7ea2fde3efc247be24c67cdf3f39e295593b/pkg/feature/api/validation.go#L1163

**Comment by cre8ivejp** [comment]
> We have validation on server side here
> 
> https://github.com/bucketeer-io/bucketeer/blob/25ed7ea2fde3efc247be24c67cdf3f39e295593b/pkg/feature/api/validation.go#L1162

I think the validation it's not working on the server because I could save the same 2 flags in the same rule.
Could you verify it, please?

**Comment by kentakozuka** [comment]
@cre8ivejp Fixed 👍

**Review by cre8ivejp — APPROVED** [review]
Nice!

**Pull request merged**
