### PR TITLE
ci: add proto-go-check command

### PR DESCRIPTION
**Pull request by ono-max**
This PR cherry-picks https://github.com/bucketeer-io/bucketeer/pull/408.

As https://github.com/bucketeer-io/bucketeer/pull/398#issuecomment-1579930517, we need to validate generated files from proto-go

### CODE REVIEW

**Review by masaaania — APPROVED** [review]
Looks good to me!

**Comment by ono-max** [comment]
Rebased.

**Review by cre8ivejp — APPROVED** [review]
Nice!

**Comment by cre8ivejp** [comment]
nit: `ci: add proto-go-check command`

**Pull request merged**
